var locale = {
    "locale": "en-US",
    "dateFormat"    : "m/d/yyyy",
    "dateDisplay"   : "m/d/yyyy",
    "timeFormat"    : "h12",
    "currency"       : "^[\\$]?[-+]?[0-9]*[\\.]?[0-9]+$",
    "currencyPrefix" : "$",
    "currencySuffix" : "",
    "groupSymbol"    : "",
    "float"          : "^[-]?[0-9]*[\\.]?[0-9]+$",
    "shortmonths"    : ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    "fullmonths"     : ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    "shortdays"      : ["M", "T", "W", "T", "F", "S","S"],
    "fulldays"       : ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    "dataType": "JSON",
    "phrases" : {
        "Detalii":"Details",
        "Salveaza":"Save",
        "Sterge":"Delete",
        "Renunta":"Cancel",
        "Vizualizare":"View",
        "Descarca":"Download",
        "Adaugare TVV Nou la Extensie Noua":"Add TVV to New Extension",
        "Adaugare TVV Nou la Extensie Existenta":"Add TVV to Existing Extension",
        "Modificare TVV existent":"Modification of Existing TVV",
        "Actualizare TVV la Extensie Noua":"Update TVV to New Extension",
        "Extinderea omologarii de tip":"Extension of Type Approval",
        "Omologare CE/CEE-ONU de tip Serie nelimitata":"CE/CEE-ONU Type Approval Unlimited Series",
        "Omologare CE/National de tip Serie mica":"CE/National Type Approval Limited Series",
        "CEC":"CEC",
        "Dispozitie plata":"Payment Order",
        "Numerar":"Cache",
        "Tip activitate:":"Activity:",
        "Tip completare date:":"Data Completion Method:",
        "Data WVTA:":"WVTA Release Date:",
        "Solicitati eliberare cerificat?":"Demand Certificate?",
        "Solicitati incercari?":"With tests?",
        "Nr. omologare baza:":"Base Type Approval Nr.:",
        "Metoda plata:":"Payment method:",
        "Responsabil cerere:":"Application responsible:"  ,
        "Reprezentant legal:":"Legal Representative:",
        "Observatii:":"Observations:",  
        " Salveaza":" Save",
        " Renunta":" Cancel",  
        "Tip actiune:":"Action Type:",  
        "Grupa:":"Group:",
        "Categorie:":"Category:",
        "Categorie folosinta:":"Category of Use:",
        "Caroserie:":"Body:",
        "Tip Motor:":"Engine Type:",
        "Tip conf. producator:":"Type according prod.:",
        "Producator:":"Manufacturer:",
        "Marca:":"Make:",
        "Tip:":"Type:",
        "Versiune:":"Version:",
        "Varianta:":"Variant:",
        "Denumire Comerciala:":"Commercial Name:",
        "Marca":"Make",
        "Tip":"Type",
        "Versiune":"Version",
        "Varianta":"Variant",
        "Denumire Comerciala":"Commercial Name",
        "Caroserie:":"Body:",
        "Categorie:":"Category:",
        "Categorie Folosinta:":"Category of Use:",
        "Act Normativ:":"Regulatory act:",
        "Tip Act Normativ:":"Type of Regulatory Act:",
        "Solicitare act echivalent:":"Require equivalent:",
        "Amendament":"Amendament",
        "Amendament:":"Amendament",
        "REGULAMENTE":"REGULATIONS",
        "REGULAMENTE UE":"UE REGULATIONS",
        "DIRECTIVE":"DIRECTIVES",
        "Nr. Omologare nou":"New Type Approval",
        "Extindere":"Extension",
        "Revizie":"Revision",
        "Corectie":"Corection",
        "--Alegeti din lista--":"--Select from list--",

        "Sterge fisier":"Delete file",
        "Incarca fisier":"Upload file",
        "Fisier neincarcat inca...":"File not uploaded yet...",
        "Incarcat":"Uploaded",
        "Eroare incarcare":"Error uploading",
        "Se incarca ...":"Uploading...",
        "Incarca":"Upload",
        " Incarca":" Upload",
        "Alege fisiere":"Choose files",
        " Alege...":" Browse...",
        "Reset":"Reset",
        " Reset":" Reset",
        "Trageti fisiere aici":"Drag files here",

        //menu
        "Program":"Program",
        // "Inchide":"Exit",
        "Reincarca":"Reload",
        "Fereastra":"Window",
        "Formular CIV":"VIC Form",
        "Aplicatia tipareste pe formularul ":"Printing on ",
        "CIV Nou":"New Form",
        "CIV vechi":"Old Form",
        "! Doriti schimbarea formularului?":"! Do you want to change this?",

        "Comenzi C.I.V.":"V.I.C. Orders",
        "Comanda noua":"New order",
        "Lista comenzi Grivita":"Order list Grivita",
        "Lista comenzi Voluntari":"Order list Voluntari",
        "Lista comenzi Pitesti":"Order list Pitesti",
        "Toata lista":"All",
        "Situatie plati":"Payments status",
        "Situatie CIV-uri":"VIC's status",
        "Sfarsit serie":"End of series",
        "Lista vehicule":"Vehicle list",
        "CIV Individual":"Individual VIC",
        "Lista comenzi":"Orders list",
        "Situatie CIV":"VIC's status",
        "Cauta VIN":"Search VIN",
        "Operatii CIV":"VIC Operations",
        "Arhivare":"Archive",
        "Anulare":"Cancel",
        "Cereri Nr. Omologare":"Type Approval No. Requests",
        'Cerere noua':"New Request",
        "Lista":"List",
        "Utilizator":"User",
        "Autentificare":"Login",
        "Profil":"Profile",
        "Inchide sesiunea":"Logoff",
        "Setari proxy":"Proxy settings",
        "Ajutor":"Help",
        "Manual utilizare": "User Manual",


        //comenzi
        "Nr. inregistrare RAR":"RAR Registration No.",
        "Data Inregistrare":"Registration Date",
        "Nr. registru client":"Client Registration No.",
        "Data registru client":"Client Registration Date",
        "Inchide":"Close",
        "Salveaza":"Save",
        "Editare":"Edit",
        "Instiintare plata":"Payment notification",
        "Raport":"Report",
        "Raport XLS":"xls Report",
        "Transmite comanda!":"Post order!",
        "Sigur finalizati aceasta comanda?":"Are you sure you want to finalize this order?",
        "Tipar":"Print",
        "Verificare":"Verify",
        "Arhivare":"Archive",
        "Anulare":"Cancel",
        "Nr.Comanda":"Order No.",
        "Nr. Vehicule":"Vehicles",
        "Data":"Date",
        "Nr client":"Client order no.",
        "Data client":"Client order date",
        "Serie CIV":"VIC serial",
        "Finalizata":"Completed",
        "Depusa":"Posted",
        "Prelucrata":"Processed",
        "FACTURAT-NEINCASAT":"NOT CASHED YET",
        "NEPRELUCRAT":"NOT PROCESSED YET",
        "Adaugati vehicule":"Add vehicles",
        "In lucru - OK":"In progress - OK",
        "In lucru - Vehicule invalide":"In progress - invalid vehicles",
        "In curs de transmitere":"Sending",
        "Depusa - asteapta prelucrare":"Posted - wait for processing",
        "Prelucrata - OK":"Processed - OK",
        "Verificat - OK":"Verified - OK",
        "Tiparit":"Printed",
        "In prelucrare":"Processing",
        "Alege fisier":"Choose file",
        "Data tipar":"Print date",
        "Punct de lucru":"Issued from",
        "Numar bucati":"Items",
        "Data factura":"Invoice date",
        "Suma incasata":"Amount",
        "Serie factura":"Invoice serial",
        "Nr factura":"Invoice no",
        " Beneficiari:":"Clients",
        "Nr. Identificare":"VIN No.",
        "Serie Motor":"Engine Serial",
        "Cat. EU":"EU Category",
        " Incarca vehicule":"Load vehicles",
        "Eroare la transmitere! Verificati fisierul!":"Error sending file!",
        "Fata(Anvelopa/Janta):":"Front(Tyre/Rim)",
        "Spate(Anvelopa/Janta):":"Back(Tyre/Rim)",
        "Anvelope echipare standard":"Standard equipment",
        "Anvelope echipare optionala":"Optional equipment",




        //anvelope
        "Anvelopa:":"Wheel tyre:",
        "Anvelopa":"Wheel tyre",
        "Janta":"Wheel rim",
        "Axa:":"Axle:",
        "Axa":"Axle",
        "Axa fata:":"Front axle:",
        "Axa spate:":"Rear axle:",
        "Idem spate:":"Same on rear:",
        "Fata":"Front",
        "Spate":"Rear",
        
        //registru
        "Nr. Extensie:":"Extension no.:",
        "Data Extensie:":"Extension Date:",
        "Date lucru cerere":"Work area",
        "Date existente TVV":"Existing data",
        "Date TVV":"TVV data",
        "Varianta noua":"Add variant",
        "Versiune noua":"Add version",
        "Notificare":"Notification",
        "Inregistrarile au fost sterse!":"Records deleted!",
        "Activitate":"Activity",
        "Modificare extensie":"Extension update",
        "Date incomplete!":"Incomplete data!",
        "Adaugare varianta":"New variant",
        "Adaugare versiune":"New version",
        "Numar registru":"Register No.",
        "Transfera TVV selectat":"Transfer selected TVV",
        "Acest TVV exista deja la extensia selectata!":"This TVV already exists on selected extension!",
        "Va rog sa selectati o extensie in tabelul de mai sus!":"Please select an extension from above table!",
        "Extensie":"Extension",
        "Date existente WVTA":"Existing WVTA data",
        "Transfera extensia":"Transfer extension",
        "Extensia selectata exista deja!":"Selected extension already exists!",
        "Adauga extensie":"Add extension",
        "Sterge extensia":"Delete extension",
        "Extensia nr. ":"Extension no. ",
        "Nr. Registru": "Register No.",
        "Se asteapta generarea...":"Waiting...",
        "Categorie CE:":"EC Category:",
        "Denumire:":"Commercial Name:",
        "Mod omologare:":"Approval type:",
        "Numar axe:":"Axles:",
        "Acest TVV exista in baza de date la acest WVTA!<br>Doriti sa continuati cu datele introduse?":"This TVV already exists in the database!<br>Do you wish to continue with existing data?",

        //date tehnice
        //mase
        "Masa proprie (kg)":"Mass in running order (kg)",
        "Masa tehnica totala (kg)":"Tech. perm. max. laden mass (kg):",
        "Masa tehnica axa (kg) 1":"Tech. perm. max. axle (kg) 1",
        "Masa tehnica axa (kg) 2":"Tech. perm. max. axle (kg) 2",
        "Masa tehnica axa (kg) 3":"Tech. perm. max. axle (kg) 3",
        "Masa tehnica axa (kg) 4":"Tech. perm. max. axle (kg) 4",
        "Masa tehnica axa (kg) 5":"Tech. perm. max. axle (kg) 5",
        "Masa ansamblu (kg)":"Tech. perm. max. comb. (kg)",
        "Remorcabila cu disp (kg)":"Tech. perm. max. towable braking (kg)",
        "Remorcabila fara disp (kg)":"Tech. perm. max. towable non braking (kg)",
        "Masa utila (kg)":"Load mass (kg)",
        "Masa plafon (kg)":"Ceiling mass (kg)",
        "Masa pe carlig (kg)":"Tech. perm. max. coupling point (kg)",
        //dimensiuni
        "Lungime (mm)":"Length (mm)",
        "Latime (mm)":"Width (mm)",
        "Inaltime (mm)":"Height (mm)",
        "Ampatament (mm) 1":"Wheel base (mm) 1",
        "Ampatament (mm) 2":"Wheel base (mm) 2",
        "Ampatament (mm) 3":"Wheel base (mm) 3",
        "Ampatament (mm) 4":"Wheel base (mm) 4",
        "Ecartament (mm) 1":"Axle spacing (mm) 1",
        "Ecartament (mm) 2":"Axle spacing (mm) 2",
        "Ecartament (mm) 3":"Axle spacing (mm) 3",
        "Ecartament (mm) 4":"Axle spacing (mm) 4",
        "Ecartament (mm) 5":"Axle spacing (mm) 5",
        "Consola spate (mm)":"Rear overhang (mm)",
        //poluare
        "Doc. Omologare":"Approval doc.",
        "Particule":"Particulates",
        "Combustibil alternativ":"Alternate fuel",
        "Nr Omologare GPL":"LPG Approval No.",
        "CO2 combinat alternativ (g/km)":"Alternate CO2 mass (g/km)",
        "Poluare":"National emission code",
        "Filtru particule":"Particulates filter",
        "Zgomot mers (dbA)":"Sound level drive-by (dbA)",
        "Zgomot stationare (dbA)":"Sound level stationary (dbA)",
        "Turatie zgomot stationare":"Sound level engine speed",
        "CO2 combinat (g/km)":"CO2 comb. emission",
        "Cod general ecoinovatie":"Ecoinovation code",
        "Total reduceri CO2(g/km)":"CO2 emission reduction(g/km)",
        "Consum urban (l/100km)":"Fuel consumption urban (l/100km)",
        "Consum extraurban (l/100km)":"Fuel consumption extraurban (l/100km)",
        "Consum mixt (l/100km)":"Fuel consumption mixt (l/100km)",
        "CO2 WLTP combinat (g/km)":"CO2 WLTP combined (g/km)",
        "CO2 NEDC combinat (g/km)":"CO2 NEDC combined (g/km)",
        "Consum faza joasa (l/100km)":"Fuel consumption low phase (l/100km)",
        "Consum faza inalta (l/100km)":"Fuel consumption high phase (l/100km)",
        "Consum faza medium (l/100km)":"Fuel consumption medium phase (l/100km)",
        "Consum combinat (l/100km)":"Fuel consumption combined (l/100km)",
        "Masa test (kg)":"Test mass (kg)",
        "Cod general ecoinovatie WLTP":"Ecoinovation code WLTP",
        "Total reduceri CO2 WLTP":"CO2 emission reduction WLTP",
        "Consum energie electrica":"Energy consumption",
        "Factor deviere":"Deviation factor",
        "Factor verificare":"Verification factor",
        //transmisie
        "Tip tractiune":"Power train",
        "Tip transmisie":"Gearbox type",
        "Nr. trepte inainte":"Forward gear no.",
        "Nr. trepte inapoi":"Backward gear no.",
        "Viteza maxima (km/h)":"Maximum speed(km/h)",
        //axe
        "Tip axa 1":"Axle type 1",
        "Tip axa 2":"Axle type 2",
        "Tip axa 3":"Axle type 3",
        "Tip axa 4":"Axle type 4",
        "Tip axa 5":"Axle type 5",
        "Tip suspensie axa 1":"Suspension type axle 1",
        "Tip suspensie axa 2":"Suspension type axle 2",
        "Tip suspensie axa 3":"Suspension type axle 3",
        "Tip suspensie axa 4":"Suspension type axle 4",
        "Tip suspensie axa 5":"Suspension type axle 5",
        "Grup axa 1":"Axle group 1",
        "Grup axa 2":"Axle group 2",
        "Grup axa 3":"Axle group 3",
        "Grup axa 4":"Axle group 4",
        "Grup axa 5":"Axle group 5",
        //alte date
        "Locuri in fata":"Front seats",
        "Locuri scaune":"Seated places",
        "Locuri picioare":"Standing places",
        "Locuri total":"Total places",
        "Capacitate rezervor 1 (l)":"Fuel tank capacity 1 (l)",
        "Capacitate rezervor 2 (l)":"Fuel tank capacity 2 (l)",
        "Sistem propulsie":"Propulsion",
        "Tip franare":"Braking system",
        "Tip asistare directie":"Steering assist type",
        "Echipare ADR":"ADR Equipment",
        "Putere 30min electric (kW)":"Max 30 min power (kW)",
        "Putere neta electric (kW)":"Max net power (kW)",
        "Putere orara electric (kW)":"Max houtly output (kW)",
        "Consum WH/km":"Energy consumption WH/km",
        "Raport putere/masa (moto)":"Power/mass ratio (moto)",
        //tabs
        "Date TVV":"TVV Data",
        "Date generale":"General info",
        "Mase":"Masses",
        "Dimensiuni":"Dimensions",
        "Axe":"Axles",
        "Alte Date":"Others",
        "Anvelope":"Wheels",
        "Motor":"Engine",
        "Transmisie":"Power train",
        "Poluare":"Emissions",
        "Componente/Sisteme":"Syst./Components",
        "Mentiuni":"Mentions",
        "Importa datele de la extensia anterioara":"Import data from previous extension",
        "Inchide":"Close",
        "Va rugam asteptati":"Please wait",
        "Inregistrarea a fost salvata!":"Record saved!",
        "Inregistrarea nu a fost salvata!":"Error saving record!",
        "Sigur doriti aducerea datelor de la extensia anterioara?<br>Datele existente se vor sterge!":"Are you sure you want to import data?<br>Existing data will be erased!",
        "Inregistrarea contine erori! Verificati datele generale!":"Record has errors! Check General info tab!",
        "Eroare":"Error",
        //motor
        "Cod motor":"Engine code",
        "Putere(kW)":"Net power(kw)",
        "Putere(CP)":"Net power(HP)",
        "Cilindree":"Capacity",
        "Tip motor":"Engine type",
        "Transfera selectia":"Transfer selected row",
        "Motorul selectat exista deja!":"Selected engine already exists",
        "Cod poansonat":"Engine code as marked",
        //comanda
        "Text comanda":"Order text",
        "Text subsol":"Footer text",
        "FINALIZATA":"COMPLETED",
        "EMISA":"ISSUED",
        "Stare Comanda":"Order satus",
        "Obiect comanda":"Order object",
        //deviz
        "Autovehicule":"Vehicles",
        "Remorci":"Towed vehicles",
        "Regulamente CEE-ONU":"EEC Regulations",
        "Directive-Regulamente CE":"EC Directives-Regulations",
        //dosare
        "Omologare Tip":"Type Approval",
        "Inregistrare Nationala":"National Registration",
        "FINALIZAT":"COMPLETED",
        "IN LUCRU":"IN PROGRESS",
        "ANULAT":"CANCELED",
        "Sigur stergeti aceasta inregistrare?":"Delete this record?",
        "Generare Nr.":"Generate No.",
        "Nr Omologare generat!":"Type Approval No. Generated!",
        "TIP":"TYPE",
        "NR. ACT":"NORM. NO.",
        "NR. AMENDAMENT":"AMENDAMENT NO.",
        "Nr. Omologare Baza":"Base Type App. No.",
        "Nr. Omologare":"Type App. No.",
        "Fisier":"File",
        "Nume fisier":"File name",
        "Data depunere":"Submission date",
        "Nr. Raport":"Report No.",
        "Data Raport":"Report Date",
        "Stare Raport":"Report Status",
        "Raport incarcat":"Report loaded",
        "Nr. comanda":"Order no.",
        "Data comanda":"Order date",
        "Stare comanda":"Order status",
        "Raport Incercari Incarcat!":"Test Report loaded!",
        "Eroare la incarcare!":"Error loading report!",
        //email
        "De la":"From",
        "Data":"Date",
        "Catre":"To",
        "Subiect":"Subject",
        "Nou":"New",
        "Mesaj corespondenta":"Mail message",
        "Nu s-a putut incarca agenda de adrese pentru acest dosar!":"Contacts could not be loaded!",
        "Trimite":"Send",
        "Anuleaza":"Cancel",
        "Email trimis cu success!":"Email sent!",
        "Eroare la transmitere!":"Error sending mail!",
        "Numar deviz":"Payment estimate no.",
        "Comanda":"Order",
        "Data deviz":"Payment estimate date",
        "Valoare deviz":"Ammount to pay",
        "Stare deviz":"Payment status",
        'ACHITAT':"PAYED",
        "NEACHITAT":"NOT PAYED",
        "ANULAT":"CANCELED",
        "Data achitarii":"Payment date",
        "Data acceptare":"Accept date",
        "Aprobat":"Approved",
        "APROBAT":"APPROVED",
        "NEAPROBAT":"NOT APPROVED YET",
        "Date factura":"Invoice date",
        "Descriere":"Description",
        //dosar
        "Valoare incorecta!":"Incorrect value!",
        "Nr. Dosar":"File No.",
        "Data Dosar":"File Date",
        "Data Finalizare":"Completion Date",
        "Stare":"Status",
        "Beneficiar":"Client",
        "Coordonator":"Coordinator",
        "Tip dosar":"File Type",
        "Stare plata":"Payment status",
        "FARA DEVIZ":"NO PAYMENT",
        "Vechi":"Old",
        "Achitat":"Payed",
        "Neachitat":"Not payed",
        "Finalizat":"Completed",
        "In lucru":"In progress",
        "Anulat":"Canceled",
        "Nr. DOT":"DOT No.",
        "Data DOT":"DOT Date",
        "Numar act":"Normative no.",
        "Nr. Registru(RAR)":"Register No.(RAR)",
        "Nr. Deviz":"Estimate No.",
        "Date principale":"Main informations",
        "Documentatie":"Documentation",
        "Devize":"Payments",
        "Corespondenta":'Email',
        "Obiect":"Object",
        "Acte normative":"Regulatory acts",
        "Comenzi":"Orders",
        "Certificate":"Certificates",
        //registru dosare
        "Ordine CIV":"CIV Order",
        "Date lucru dosar":"Work area",
        "Meniu":"Menu",
        "Extensia are TVV-uri atasate! Va rugam stergeti mai intai TVV-urile si apoi extensia!":"This extension has TVV attached and cannot be deleted!",
        "Adauga mentiunea":"Add mention",
        "Componenta selectata exista deja":"Selected component already exists!",
        "Turatie putere":"Engine speed",
        "Act normativ":"Regulatory act",
        "Aplicare":"Applies to",
        "Cerinta":"Demand",
        "Data Aplicarii":"Applies staring",
        "Data Expirarii":"Expires",
        "Coloana":"Column",
        "CERINTA SE SELECTEAZA DIN LISTA DACA E CAZUL!":"DEMAND IS SELECTED FROM LIST IF APPLICABLE",
        "Categorii":"Categories",
        "Va rog selectati o valoare in coloana CERINTA":"Please select a value in DEMAND column",
        "Valideaza datele!":"Validate data!",
        "Certificat":"Communication",
        "Atestat":"Certificate",
        "Fisa":"Record",
        "Sigur validati acest numar?":"Validate this data?",
        "ATENTIE!<br>TVV-ul nu este valid deoarece nu indeplineste cerintele ":"WARNING!<br>This TVV is not valid as it does not meet the requirements of ",
        " intrate in vigoare la data ":" mandatory begining with ",
        "Sigur validati?":"Are you sure you want to validate?",
        "Datele au fost validate!":"Data has been validated!",
        "Datele existente se vor sterge! Sigur doriti inlocuirea datelor?":"Existing data will be deleted! Are you sure?",

        "Intrare:":"Entry No.:",
        "Tip dosar:":"File type:",
        "Mod deschidere:":"Opening mode:",
        "Data intrare DOT:":"Date of entry:",
        "Nr. cerere client:":"Client application no.:",
        "Data cerere client:":"Client application date:",
        "Nr. intrare RAR:":"RAR submission no.:",
        "Data intrare RAR:":"RAR submission date:",
        "Stare dosar:":"File status:",
        "Coordonator:":"Coordinator:",
        "Beneficiar:":"Client:",
        "Data finalizare:":"Completion date:",
        "Observatii":"Observations",
        "Inapoi la lista":"Back to list",
        "Data finalizare":"Completion date",
        "Stare dosar":"File status",
        "Nr. cerere client":"Client application no.",
        "Data deschidere":"Opening date",
        "Nr. dosar":"File no.",
        "Mesaj":"Message",
        "Trimise":"Sent",
        "Primite":"Received",
        "Tip motor:":"Engine type:",
        "Dosar":"File"
        
    }
};
module.exports = locale;
